---
grails:
    profile: web
    codegen:
        defaultPackage: ccn_2
    spring:
        transactionManagement:
            proxies: false
    mail:
        host: "smtp.gmail.com"
        port: 465
        username: "@gmail.com"
        password: ""
        props:
            mail.smtp.auth: "true"
            mail.smtp.socketFactory.port: "465"
            mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
            mail.smtp.socketFactory.fallback: "false"

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: rudsom
    password: 16..

environments:
    development:
        dataSource:
            username: rudsom
            password: smolder
            dbCreate: update
            url: jdbc:mysql://localhost:3306/ccn2
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/ccn2
    production:

        dataSource:
            username: rudsom
            password: 16local31
            pooled: true
            dbCreate: update
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://ebdb.casdnxwazxad.sa-east-1.rds.amazonaws.com:3306/ebdb?user=rudsom&password=16...
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            properties:
              validationQuery: SELECT 1
              testOnBorrow: true
              testOnReturn: true
              testWhileIdle: true
              timeBetweenEvictionRunsMillis: 1800000
              numTestsPerEvictionRun: 3
              minEvictableIdleTimeMillis: 1800000

